# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pockity
email: support@pockity.app
description: >- # this means to ignore newlines until "baseurl:"
  Simple personal budgeting and expense tracking for iOS & iPadOS (and soon, macOS)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pockity.app" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pockityapp
github_username:  pockity
keywords: pockity,budget,manager,finance,tracker,expense,expenses,subscriptions,accounts,category,categories,appstore,iOS,iPadOS,Apple,iPhone,iPad

# Build settings
plugins:
  - jekyll-local-theme

include: ['_pages']  

defaults:
- scope:
    path: ""
    type: pages
  values:
    layout: default
- scope:
    path: ""
    type: posts
  values:
    layout: post
- scope:
    path: ""
    type: drafts
  values:
    layout: post

# Theme Settings
local_theme: launchkit
caption: Simple personal budgeting and expense tracking